[project]
name = "deepsea_ai_agent"
version = "0.1.0"
description = "deepsea-ai-agent using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[google-genai,tools]==1.14.4",
]

[project.scripts]
deepsea_ai_agent = "deepsea_ai_agent.main:run"
run_crew = "deepsea_ai_agent.main:run"
train = "deepsea_ai_agent.main:train"
replay = "deepsea_ai_agent.main:replay"
test = "deepsea_ai_agent.main:test"
run_with_trigger = "deepsea_ai_agent.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
